/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthValidateEmailRouteImport } from './routes/auth.validate-email'
import { Route as AuthCheckEmailRouteImport } from './routes/auth.check-email'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AppVoiceRouteImport } from './routes/_app/voice'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppPulseRouteImport } from './routes/_app/pulse'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPeaceRouteImport } from './routes/_app/peace'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppVoiceSurveyIdRouteImport } from './routes/_app/voice.$surveyId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthValidateEmailRoute = AuthValidateEmailRouteImport.update({
  id: '/validate-email',
  path: '/validate-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppPulseRoute = AppPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPeaceRoute = AppPeaceRouteImport.update({
  id: '/peace',
  path: '/peace',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceSurveyIdRoute = AppVoiceSurveyIdRouteImport.update({
  id: '/$surveyId',
  path: '/$surveyId',
  getParentRoute: () => AppVoiceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/peace': typeof AppPeaceRoute
  '/profile': typeof AppProfileRoute
  '/pulse': typeof AppPulseRoute
  '/rewards': typeof AppRewardsRoute
  '/voice': typeof AppVoiceRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/validate-email': typeof AuthValidateEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/voice/$surveyId': typeof AppVoiceSurveyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/peace': typeof AppPeaceRoute
  '/profile': typeof AppProfileRoute
  '/pulse': typeof AppPulseRoute
  '/rewards': typeof AppRewardsRoute
  '/voice': typeof AppVoiceRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/validate-email': typeof AuthValidateEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/voice/$surveyId': typeof AppVoiceSurveyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/peace': typeof AppPeaceRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/pulse': typeof AppPulseRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/voice': typeof AppVoiceRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/validate-email': typeof AuthValidateEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/voice/$surveyId': typeof AppVoiceSurveyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/opportunities'
    | '/peace'
    | '/profile'
    | '/pulse'
    | '/rewards'
    | '/voice'
    | '/auth/check-email'
    | '/auth/validate-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/voice/$surveyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/opportunities'
    | '/peace'
    | '/profile'
    | '/pulse'
    | '/rewards'
    | '/voice'
    | '/auth/check-email'
    | '/auth/validate-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/voice/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/opportunities'
    | '/_app/peace'
    | '/_app/profile'
    | '/_app/pulse'
    | '/_app/rewards'
    | '/_app/voice'
    | '/auth/check-email'
    | '/auth/validate-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/_app/voice/$surveyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/validate-email': {
      id: '/auth/validate-email'
      path: '/validate-email'
      fullPath: '/auth/validate-email'
      preLoaderRoute: typeof AuthValidateEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pulse': {
      id: '/_app/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AppPulseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peace': {
      id: '/_app/peace'
      path: '/peace'
      fullPath: '/peace'
      preLoaderRoute: typeof AppPeaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/$surveyId': {
      id: '/_app/voice/$surveyId'
      path: '/$surveyId'
      fullPath: '/voice/$surveyId'
      preLoaderRoute: typeof AppVoiceSurveyIdRouteImport
      parentRoute: typeof AppVoiceRoute
    }
  }
}

interface AppVoiceRouteChildren {
  AppVoiceSurveyIdRoute: typeof AppVoiceSurveyIdRoute
}

const AppVoiceRouteChildren: AppVoiceRouteChildren = {
  AppVoiceSurveyIdRoute: AppVoiceSurveyIdRoute,
}

const AppVoiceRouteWithChildren = AppVoiceRoute._addFileChildren(
  AppVoiceRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPeaceRoute: typeof AppPeaceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPulseRoute: typeof AppPulseRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppVoiceRoute: typeof AppVoiceRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPeaceRoute: AppPeaceRoute,
  AppProfileRoute: AppProfileRoute,
  AppPulseRoute: AppPulseRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppVoiceRoute: AppVoiceRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthValidateEmailRoute: typeof AuthValidateEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthValidateEmailRoute: AuthValidateEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
